#!/usr/bin/env ruby

extensions = %w[
  js jsx ts
  html css less scss
  md mdx dfm
  yml yaml
  rb
].map { |ext| "'*.#{ext}'" }.freeze

changes = `git diff --name-only --cached -- #{extensions.join(' ')}`
changes = changes.split

if changes.empty?
  puts "No staged changes"
else
  puts `#{File.expand_path('..', __dir__)}/node_modules/.bin/prettier --write #{changes.join(' ')}`
  `git add #{changes.join(' ')}`
end
